 - name: configuring catalogue server
    hosts: catalogue
  become: yes
  tasks:
  - name: disable dnf module
    ansible.builtin.command: dnf module disable nodejs -y
  - name: enable dnf module
    ansible.builtin.command: dnf module enable nodejs:20 -y
  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present
  - name: create an app directory
    ansible.builtin.file:
      path: /app
      state: directory
  - name: craete a catalogue user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      system: true
      home: /app
  - name: download catalogue code
    ansible.builtin.get_url:
      url : https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
      dest: /tmp/catalogue.zip
   # this module thinks file exist on ansible control server, needs to extract on to remote machine
   # remote_src: yes means files already exist in catalogue server
  - name: unarchive the code
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes
  - name: install dependencies
    community.general.npm:
      path: /app
  - name: copy catalogue servive to systemd service
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service
  - name: reload the catalogue service
    ansible.builtin.systemd_service:
      daemon-reload: true
  - name: start the service
    ansible.builtin.service:
      name: catalogue
      state: started
      enabled : yes
  - name: copy mongo repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo
  - name: install mongodb
    ansible.builtin.dnf:
      name: mongodb-mongosh
      state: present
  - name: check products loaded or not
    ansible.builtin.command: mongosh --host mongodb.saijyo.store --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
    register: catalogue_output
  - name: verify the command catalogue_output
    ansible.builtin.debug:
      msg : "{{ catalogue_output }}"
  - name: load products
    ansible.builtin.shell: mongosh --host mongodb.saijyo.store < /app/db/master-data.js
    when: catalogue_output.stdout | int < 0